[information]
name = "noxmodus"
background = "dark"
author = "Lano Puljic"

# The format is [foreground, background, style, special ,blend]
# Style Options:
#    o: standout
#    u: underline
#    c: undercurl
#    d: underdouble
#    t: underdotted
#    h: underdashed
#    s: strikethrough
#    i: italic
#    b: bold
#    r: reverse
#    n: nocombine


[palette]
bg                          = '#111111'
fg                          = '#999999'
lighteter_black             = '#151515'
gray01                      = '#2F2F2F'
gray02                      = '#666666'
gray03                      = '#b6b6b5'
gray04                      = '#7c8c95'
gray05                      = '#8c8c8c'
gray06                      = '#a0a0a0'
white                       = '#E1E1E1'
green                       = '#97BC62'
blue                        = '#719597'
purple                      = '#B180D7'
red                         = '#f43841'
orange                      = '#e67300'
yellow                      = '#FAC03B'
grayish_blue                = '#96a6c8'
light_blue                  = '#88afa2'
md_blue                     = '#569CD6'
md_orange                   = '#A47663'


cursor_fg                   = '#415062'
cursor_bg                   = '#AbAbAf'

DiffAdd                     = '#294841'
DiffDelete                  = '#6A2835'
DiffChange                  = '#49423C'
DiffText                    = '#9A6F43'


[editor]
# Misc
Normal                      = 'gray03 bg'                      # Normal textj
NormalNC                    = 'gray03 bg'                      # Normal text in non-current windows.
Cursor                      = 'cursor_fg cursor_bg'            # Character under the cursor
Underlined                  = '- - u'
SpecialKey                  = 'fg - b'
NonText                     = 'gray02'
Insert                      = 'red orange'
MsgArea                     = 'fg bg'
VertSplit                   = 'gray01'                         # The column separating vertically split windows

# Lines
LineNr                      = 'gray01 -'
CursorLineNr                = 'yellow bg'
CursorLine                  = '- gray01'
SignColumn                  = '- bg'
ColorColumn                 = '- gray06'
CursorColumn                = '- gray01'

# Spelling
SpellBad                    = '- - c red'                     # Word that is not recognized by the spellchecker.
SpellCap                    = '- - c yellow'                  # Word that should start with a capital
SpellLocal                  = '- - u green'                   # Word that is recognized by the spellchecker as one that is used in another region
SpellRare                   = '- - u purple'                  # Word that is recognized by the spellchecker as one that is hardly ever used

# Messages
ErrorMsg                    = 'red bg b'
WarningMsg                  = 'orange bg'
ModeMsg                     = 'fg bg'
MoreMsg                     = 'yellow'
Error                       = 'red - b'

# Visual
Visual                      = 'gray01 gray03'
VisualNOS                   = '- red'
Search                      = 'bg white'
IncSearch                   = 'bg white'

# Popup Menu
Pmenu                       = 'fg gray01'
PmenuSel                    = 'white gray02'
PmenuSbar                   = 'fg gray01'
PmenuThumb                  = 'fg gray03'         # Changes colour of scroll bar in floating window.

# Diff
DiffText                    = 'white DiffText'
DiffAdd                     = 'white DiffAdd'
DiffChange                  = 'white DiffChange'
DiffDelete                  = 'white DiffDelete'

# Others
WildMenu                    = 'fg bg'
Folded                      = 'gray02 -'
FoldColumn                  = 'gray06 -'
Whitespace                  = 'fg'
NormalFloat                 = '- -'               # Changes background on floating windows
FloatBoder                  = 'gray03 bg'
QuickFixLine                = '- yellow'
MatchWord                   = '- - u'
MatchParen                  = 'orange'
MatchWordCur                = '- - u'
MatchParenCur               = '- - u'
lCursor                     = 'cursor_fg cursor_bg'
CursorIM                    = 'cursor_fg cursor_bg'
TermCursor                  = 'cursor_fg cursor_bg'
TermCursorNC                = 'cursor_fg cursor_bg'
Conceal                     = 'fg'
Directory                   = 'gray06'
Substitute                  = 'bg gray03'
Question                    = 'yellow'
EndOfBuffer                 = 'bg'
TabLine                     = 'gray06 bg'
TabLineSel                  = 'fg bg'
TabLineFill                 = 'bg bg'

[Code]
Comment                     = 'gray02 - i'
Title                       = 'gray05 - b'
String                      = 'light_blue'              # Anything is the quoates is a string
Character                   = 'gray03'                  # A character constant: 'c', '\n'
Number                      = 'gray04'                  # A number constant: 234
Float                       = 'gray04'                  # A floating point constant: 2.3e10
Boolean                     = 'grayish_blue'            # A boolean constant: TRUE, false
Constant                    = 'light_blue'              # Any Contstand e.g. terrafrom ( aws_)
Type                        = 'grayish_blue'            # int, long, char, etc. (terraform resource)
StorageClass                = 'white'                   # static, register, volatile
Structure                   = 'white'                   # struct, union, enum
Typedef                     = 'white'                   # A typedef
PreProc                     = 'grayish_blue'            # was gray05
Include                     = 'grayish_blue'            # preprocessor #include
Define                      = 'gray05'                  # preprocessor #define
Macro                       = 'gray05'
PreCondit                   = 'gray05'                  # if, else, endif, etc.
Statement                   = 'grayish_blue'
Conditional                 = 'grayish_blue'            # preprocessor #if, #then, #else, #endif, switch, case
Repeat                      = 'grayish_blue'            # for, do, while
Label                       = 'gray03'                  # case, default,
Operator                    = 'gray03'                  # " =, >=, :="
Keyword                     = 'grayish_blue'            # func,range, type, struct, const
Variable                    = 'white'
Exception                   = 'gray03'                  # Try, catch, throw
Identifier                  = 'white'                   # Any variable name
Function                    = 'light_blue'              # Function Name (also: methods for classes)
Special                     = 'grayish_blue'            # any special symbols
SpecialChar                 = 'white'                   # special character in a constant e.g \n
Tag                         = 'gray03'
Delimiter                   = 'gray03'                  # character that needs attention like , or . or ()
Debug                       = 'red'
Bold                        = '- - b'
Italic                      = '- - i'
Ignore                      = 'red - b'
Todo                        = 'yellow - b'

[StatusLine]
StatusLine                  = 'gray03 gray01'
StatusLineNC                = 'gray02 gray01'
StatusLineSeparator         = 'gray03'
StatusLineTerm              = 'gray03'
StatusLineTermNC            = 'gray03'

[Git]
SignAdd                     = 'green'
SignChange                  = 'orange'
SignDelete                  = 'red'
GitSignsAdd                 = 'green'
GitSignsChange              = 'orange'
GitSignsDelete              = 'red'

[Packer]
packerString                = 'orange'
packerHash                  = 'blue'
packerOutput                = 'purple'
packerRelDate               = 'gray03'
packerSuccess               = 'green'
packerStatusSuccess         = 'blue'

[Nvim-Cmp]
CmpPmenuSel                 = '- gray01'
CmpItemAbbrDeprecated       = 'gray03 - s'
CmpItemAbbrMatch            = 'white'
CmpItemAbbrMatchFuzzy       = 'white'

[NvimTree]
NvimTreeGitNew              = 'green'
NvimTreeGitRenamed          = 'green'
NvimTreeGitDeleted          = 'red'
NvimTreeGitMerge            = 'orange'
NvimTreeGitStaged           = 'green'
NvimTreeGitDirty            = 'yellow'
NvimTreeSymlink             = 'blue'
NvimTreeFolderIcon          = 'link:Directory'
NvimTreeOpenedFolderName    = '- - i'
NvimTreeGitIgnored          = '- - i'
NvimTreeEmptyFolderName     = '- - i'
NvimTreeRootFolder          = 'blue - i'

[Telescope]
TelescopeSelection          = '- gray01'
TelescopeSelectionCaret     = 'grayish_blue'
TelescopeBorder             = 'gray05'
TelescopePromptfix          = 'red'
TelescopePromptBorder       = 'grayish_blue'
TelescopeResultsBorder      = 'gray05'
TelescopePreviewBorder      = 'gray05'
TelescopeMatching           = 'yellow'
TelescopePromptPrefix       = 'grayish_blue'
TelescopePromptTitle        = 'grayish_blue'

[Navic]
NavicIconsFile              = 'white'
NavicIconsModule            = 'white'
NavicIconsNamespace         = 'white'
NavicIconsPackage           = 'white'
NavicIconsClass             = 'white'
NavicIconsMethod            = 'white'
NavicIconsProperty          = 'white'
NavicIconsField             = 'white'
NavicIconsConstructor       = 'white'
NavicIconsEnum              = 'white'
NavicIconsInterface         = 'white'
NavicIconsFunction          = 'white'
NavicIconsVariable          = 'white'
NavicIconsConstant          = 'white'
NavicIconsString            = 'white'
NavicIconsNumber            = 'white'
NavicIconsBoolean           = 'white'
NavicIconsArray             = 'white'
NavicIconsObject            = 'white'
NavicIconsKey               = 'white'
NavicIconsKeyword           = 'white'
NavicIconsNull              = 'white'
NavicIconsEnumMember        = 'white'
NavicIconsStruct            = 'white'
NavicIconsEvent             = 'white'
NavicIconsOperator          = 'white'
NavicIconsTypeParameter     = 'white'
NavicText                   = 'gray05'
NavicSeparator              = 'gray04'

[Null-ls]
NullLsInfoBorder            = 'gray03'

[Markdown]
markdownBlockquote          = 'md_orange'
markdownCode                = 'md_orange - u'
markdownCodeBlock           = 'gray03'
markdownCodeDelimiter       = 'white'
markdownH1                  = 'md_blue - b'
markdownH2                  = 'md_blue - b'
markdownH3                  = 'md_blue - b'
markdownH4                  = 'md_blue - b'
markdownH5                  = 'md_blue - b'
markdownH6                  = 'md_blue - b'
markdownListMarker          = 'md_blue'
markdownOrderedListMarker   = 'md_blue'
markdownUrl                 = 'white'
markdownLinkText            = 'md_orange'
markdownHeadingDelimiter    = 'md_blue'
markdownId                  = 'link:Identifier'
markdownItalic              = 'link:Italic'
markdownBoldItalic          = 'yellow - bi'
markdownBold                = '- - b'


[Treesitter]
## Identifiers
'@variable'                 = 'link:Variable'
'@variable.builtin'         = 'grayish_blue' # --built-in variable names (e.g. `var.somehitng`)
'@lsp.type.variable'        = '-'
