local c = require("nox-modus.palette")

local hl = vim.api.nvim_set_hl
local vim = {}

vim.set_highlights = function()
	-- editor
	hl(0, "Normal", { fg = c.fg, bg = c.bg })
	hl(0, "NormalNC", { fg = c.gray03, bg = c.bg })
	hl(0, "Cursor", { fg = c.cursor_fg, bg = c.cursor_bg })
	hl(0, "Underlined", { fg = "NONE", bg = "NONE", underline = true })
	hl(0, "SpecialKey", { fg = c.fg, bg = "NONE", bold = true })
	hl(0, "NonText", { fg = c.gray02, bg = "NONE" })
	hl(0, "Insert", { fg = c.red, bg = c.orange })
	hl(0, "MsgArea", { fg = c.fg, bg = c.bg })
	hl(0, "VertSplit", { fg = c.gray01, bg = "NONE" })
	hl(0, "LineNr", { fg = c.gray01, bg = "NONE" })
	hl(0, "CursorLineNr", { fg = c.yellow, bg = c.bg })
	hl(0, "CursorLine", { fg = "NONE", bg = c.gray01 })
	hl(0, "SignColumn", { fg = "NONE", bg = c.bg })
	hl(0, "ColorColumn", { fg = "NONE", bg = c.gray06 })
	hl(0, "CursorColumn", { fg = "NONE", bg = c.gray01 })
	hl(0, "SpellBad", { fg = "NONE", bg = "NONE", sp = c.red, undercurl = true })
	hl(0, "SpellCap", { fg = "NONE", bg = "NONE", sp = c.yellow, undercurl = true })
	hl(0, "SpellLocal", { fg = "NONE", bg = "NONE", sp = c.green, underline = true })
	hl(0, "SpellRare", { fg = "NONE", bg = "NONE", sp = c.purple, underline = true })
	hl(0, "ErrorMsg", { fg = c.red, bg = c.bg, bold = true })
	hl(0, "WarningMsg", { fg = c.orange, bg = c.bg })
	hl(0, "ModeMsg", { fg = c.fg, bg = c.bg })
	hl(0, "MoreMsg", { fg = c.yellow, bg = "NONE" })
	hl(0, "Error", { fg = c.red, bg = "NONE", bold = true })
	hl(0, "Visual", { fg = c.gray01, bg = c.gray03 })
	hl(0, "VisualNOS", { fg = "NONE", bg = c.red })
	hl(0, "Search", { fg = c.bg, bg = c.fg })
	hl(0, "IncSearch", { fg = c.bg, bg = c.fg })
	hl(0, "Pmenu", { fg = c.fg, bg = c.gray01 })
	hl(0, "PmenuSel", { fg = c.fg, bg = c.gray02 })
	hl(0, "PmenuSbar", { fg = c.fg, bg = c.gray01 })
	hl(0, "PmenuThumb", { fg = c.fg, bg = c.gray03 })
	hl(0, "DiffText", { fg = c.fg, bg = c.DiffText })
	hl(0, "DiffAdd", { fg = c.fg, bg = c.DiffAdd })
	hl(0, "DiffChange", { fg = c.fg, bg = c.DiffChange })
	hl(0, "DiffDelete", { fg = c.fg, bg = c.DiffDelete })
	hl(0, "WildMenu", { fg = c.fg, bg = c.bg })
	hl(0, "Folded", { fg = c.gray02, bg = "NONE" })
	hl(0, "FoldColumn", { fg = c.gray06, bg = "NONE" })
	hl(0, "Whitespace", { fg = c.fg, bg = "NONE" })
	hl(0, "NormalFloat", { fg = "NONE", bg = "NONE" })
	hl(0, "FloatBoder", { fg = c.gray03, bg = c.bg })
	hl(0, "QuickFixLine", { fg = "NONE", bg = c.yellow })
	hl(0, "MatchWord", { fg = "NONE", bg = "NONE", underline = true })
	hl(0, "MatchParen", { fg = c.orange, bg = "NONE" })
	hl(0, "MatchWordCur", { fg = "NONE", bg = "NONE", underline = true })
	hl(0, "MatchParenCur", { fg = "NONE", bg = "NONE", underline = true })
	hl(0, "lCursor", { fg = c.cursor_fg, bg = c.cursor_bg })
	hl(0, "CursorIM", { fg = c.cursor_fg, bg = c.cursor_bg })
	hl(0, "TermCursor", { fg = c.cursor_fg, bg = c.cursor_bg })
	hl(0, "TermCursorNC", { fg = c.cursor_fg, bg = c.cursor_bg })
	hl(0, "Conceal", { fg = c.fg, bg = "NONE" })
	hl(0, "Directory", { fg = c.gray06, bg = "NONE" })
	hl(0, "Substitute", { fg = c.bg, bg = c.gray03 })
	hl(0, "Question", { fg = c.yellow, bg = "NONE" })
	hl(0, "EndOfBuffer", { fg = c.bg, bg = "NONE" })
	hl(0, "TabLine", { fg = c.gray06, bg = c.bg })
	hl(0, "TabLineSel", { fg = c.fg, bg = c.bg })
	hl(0, "TabLineFill", { fg = c.bg, bg = c.bg })

	-- Code
	hl(0, "Comment", { fg = c.gray02, bg = "NONE", italic = true })
	hl(0, "Title", { fg = c.gray05, bg = "NONE", bold = true })
	hl(0, "String", { fg = c.light_blue, bg = "NONE" })
	hl(0, "Character", { fg = c.gray03, bg = "NONE" })
	hl(0, "Number", { fg = c.gray04, bg = "NONE" })
	hl(0, "Float", { fg = c.gray04, bg = "NONE" })
	hl(0, "Boolean", { fg = c.grayish_blue, bg = "NONE" })
	hl(0, "Constant", { fg = c.light_blue, bg = "NONE" })
	hl(0, "Type", { fg = c.grayish_blue, bg = "NONE" })
	hl(0, "StorageClass", { fg = c.fg, bg = "NONE" })
	hl(0, "Structure", { fg = c.fg, bg = "NONE" })
	hl(0, "Typedef", { fg = c.fg, bg = "NONE" })
	hl(0, "PreProc", { fg = c.grayish_blue, bg = "NONE" })
	hl(0, "Include", { fg = c.grayish_blue, bg = "NONE" })
	hl(0, "Define", { fg = c.gray05, bg = "NONE" })
	hl(0, "Macro", { fg = c.gray05, bg = "NONE" })
	hl(0, "PreCondit", { fg = c.gray05, bg = "NONE" })
	hl(0, "Statement", { fg = c.grayish_blue, bg = "NONE" })
	hl(0, "Conditional", { fg = c.grayish_blue, bg = "NONE" })
	hl(0, "Repeat", { fg = c.grayish_blue, bg = "NONE" })
	hl(0, "Label", { fg = c.gray03, bg = "NONE" })
	hl(0, "Operator", { fg = c.gray03, bg = "NONE" })
	hl(0, "Keyword", { fg = c.grayish_blue, bg = "NONE" })
	hl(0, "Variable", { fg = c.fg, bg = "NONE" })
	hl(0, "Exception", { fg = c.gray03, bg = "NONE" })
	hl(0, "Identifier", { fg = c.fg, bg = "NONE" })
	hl(0, "Function", { fg = c.light_blue, bg = "NONE" })
	hl(0, "Special", { fg = c.grayish_blue, bg = "NONE" })
	hl(0, "SpecialChar", { fg = c.fg, bg = "NONE" })
	hl(0, "Tag", { fg = c.gray03, bg = "NONE" })
	hl(0, "Delimiter", { fg = c.gray03, bg = "NONE" })
	hl(0, "Debug", { fg = c.red, bg = "NONE" })
	hl(0, "Bold", { fg = "NONE", bg = "NONE", bold = true })
	hl(0, "Italic", { fg = "NONE", bg = "NONE", italic = true })
	hl(0, "Ignore", { fg = c.red, bg = "NONE", bold = true })
	hl(0, "Todo", { fg = c.yellow, bg = "NONE", bold = true })
end

return vim
